### ISSUE TITLE
I'm pretty sure I've done everything correctly... also, it doesn't seem to be compatible with world preview and mcsr ranked mod. Will downgrading java help? 

### ISSUE THREAD

**Issue by Kejk23** [faluhub/peepoPractice#3]
Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config peepopractice.mixins.json for mod peepopractice
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config peepopractice.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_10 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.5 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by mskrss** [comment]
You need to install the latest version of Java here https://adoptium.net/temurin/releases/ (download the .msi file if you're on Windows, download the .pkg file if you're on Mac)
To get Minecraft to use that version of Java,
- If you're using MultiMC or Prism: Go to Settings > Java > Auto-detect and select the latest version you have (not necessarily the starred version). If the one you downloaded doesn't show up, click Refresh on the bottom left in the Auto-detect menu. 
 - On Prism, make sure to disable the Java compatibility check in Settings > Java
- If you're using the official Minecraft launcher: don't, install one of the above mentioned.

**Comment by Kejk23** [comment]
> You need to install the latest version of Java here https://adoptium.net/temurin/releases/ (download the .msi file if you're on Windows, download the .pkg file if you're on Mac) To get Minecraft to use that version of Java,
> 
> * If you're using MultiMC or Prism: Go to Settings > Java > Auto-detect and select the latest version you have (not necessarily the starred version). If the one you downloaded doesn't show up, click Refresh on the bottom left in the Auto-detect menu.
> * On Prism, make sure to disable the Java compatibility check in Settings > Java
> * If you're using the official Minecraft launcher: don't, install one of the above mentioned.

So need to use prism in order for this mod to work?

**Comment by mskrss** [comment]
no
you need to use a newer version of Java and updating it on the official launcher is pain

you should be using prism regardless, the official launcher sucks
